[boost]
host = "0.0.0.0"
port = 18550
relays = [
    "http://127.0.0.1:28545",
]

[relay]
host = "0.0.0.0"
port = 28545
beacon_node_url = "http://127.0.0.1:5052"

[builder]
host = "0.0.0.0"
port = 28546
beacon_api_endpoint = "http://127.0.0.1:5052"
secret_key = "0x14b6e79cbc6267c6e527b4bf7a71747d42a58b10279366cf0c7bb4e2aa455901"

[builder.engine_api_proxy]
host = "0.0.0.0"
port = 8551
engine_api_endpoint = "http://127.0.0.1:8552"

[builder.transaction_injector]
mnemonic = "work man father plunge mystery proud hollow address reunion sauce theory bonus"
chain_id = 1337
provider_url = "http://127.0.0.1:8545"
