[package]
name = "mev-build-rs"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde", "api", "serde_json"]
api = ["axum", "beacon-api-client", "tracing"]

[dependencies]
axum = { version =  "0.5.4", optional = true }
tracing = { version = "0.1", optional = true }
async-trait = "0.1.53"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0.81", optional = true }
thiserror = "1.0.30"

ssz-rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "cb08f1" }
beacon-api-client = { git = "https://github.com/sigp/beacon-api-client", rev = "c1ce3f68cb1059f7fad96b89c9bd3b2c6c402513", optional = true }
