[package]
name = "mev-boost-rs"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
futures = "0.3.21"
async-trait = "0.1.53"
pin-project = "1.0.12"
rand = "0.8.5"

url = { version = "2.2.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.30"
parking_lot = "0.12.1"

ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus" }
beacon-api-client = { git = "https://github.com/ralexstokes/beacon-api-client" }

mev-rs = { path = "../mev-rs" }
prometheus = "0.13.3"

[dev-dependencies]
rand = "0.8.5"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
httpmock = "0.6.6"
serde_json = "1.0.81"
mev-build-rs = { path = "../mev-build-rs" }
mev-relay-rs = { path = "../mev-relay-rs" }
