[package]
name = "mev-relay-rs"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
futures = "0.3.21"
async-trait = "0.1.53"

thiserror = "1.0.30"
http = "0.2.7"
url = { version = "2.2.2", default-features = false }

serde = { version = "1.0", features = ["derive"] }

beacon-api-client = { git = "https://github.com/sigp/beacon-api-client", rev = "68a4eaf4e4f0bddd6d799810f3ed78dc702091c8" }

mev-build-rs = { path = "../mev-build-rs"}
